name: tod_do_or_not_to_do
description: A beautiful Todo app with Hive integration
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  intl: ^0.19.0
  provider: ^6.1.1
  path_provider: ^2.1.2
  uuid: ^4.3.3
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
